LOAD DATA
APPEND
INTO TABLE THIRDPARTY_COUNTING FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(
CNTUPC		CHAR,
CNTDESC		DECIMAL EXTERNAL,
CNTCAT		DECIMAL EXTERNAL,
CNTCOST		CHAR,
CNTCODE1	CHAR,
CNTCODE2	CHAR,
CNTLOC		CHAR,
CNTDEPT		CHAR,
CNTCODE3	CHAR,
CNTCOST2	CHAR,
CNTQTY		CHAR,
CNTEXTCOST	CHAR,
CNTCNUF		CHAR,
CNTCODE4	CHAR,
CNTCODE5	CHAR,
CNTDEPTDESC	CHAR,
CNT500		CHAR,
CNTFILE		CONSTANT ":FILEDATA",
CNTLGFI 	RECNUM,
CNTDCRE		SYSDATE,
CNTDMAJ		SYSDATE,	
CNTUTIL		CONSTANT "3RDCNT"
)
