LOAD DATA
APPEND
INTO TABLE DUNN_PRICEGROUP FIELDS TERMINATED BY ","
TRAILING NULLCOLS
(
DNNDEPT		CHAR,
DNNSSDEPT	CHAR,
DNNCAT		CHAR,
DNNSSCAT	CHAR,
DNNCODE		CHAR,
DNNUPC		CHAR,
DNNLV		CHAR,
DNNDESC		CHAR,
DNNBRAND	CHAR,
DNNPGRP		CHAR,
DNNFILE		CONSTANT ":FILEDATA",
DNNLGFI 	RECNUM,
DNNDCRE		SYSDATE,
DNNDMAJ		SYSDATE,	
DNNUTIL		CONSTANT "DNNHUMBY"
)
